### ISSUE TITLE
multilabel usage.

### ISSUE THREAD

**Issue by tujie-jiangye** [FrenchKrab/IS2023-powerset-diarization#7]
Can you provide a demo for using multilabel model for inference.

**Comment by FrenchKrab** [comment]
It should be exactly the same as [that part of the readme](https://github.com/FrenchKrab/IS2023-powerset-diarization#using-checkpoints-in-a-pipeline), but you need to uncomment the 'threshold' parameter in the params (because multilabel model outputs a 'probability' of speaker activity (in [0,1]) that needs to be discretized with a threshold to obtain binary activity).

And of course you'll need to swap the model path to a multilabel model.
